### ISSUE TITLE
look into channel name encoding issues (comments too)?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/commentron#58]
Not sure if this broke due to the recent migration or has been happening, but happened to one of my channels that had an emoji too 
```
"@Bridge????patriots","channel_url":"lbry://@Bridge????patriots#ca170c03ec8bcf84395482a899f3be06eb2ae98c",
```

**Comment by tzarebczan** [comment]
I'm going to fix the one above but I'm sure there's many other examples.

**Comment by tzarebczan** [comment]
This would also be affecting notifications that are stored, which is a bigger issue the longer we let it go.

**Comment by tzarebczan** [comment]
This is affecting blocklists too.

**Comment by tiger5226** [comment]
Its affecting roughly ( I am sure I am capturing intentional question marks possibly) 522/719,235 channels or 0.07% of the channels. 

Since its such a tiny fraction of a percent, I suspect there is some encoding gap that we have when it gets sent from the client. I think @DispatchCommit changed Sean's parsing logic in the app to simplify it. It might be a good idea to look at a few of these examples and test it out like sean and I did together on a call to debug whats going on here.

**Comment by tzarebczan** [comment]
new channels are fine, I tested this. It's older channels that happened during the migration I'm pretty sure.

**Comment by tzarebczan** [comment]
I fixed all the channels in the channels table by querying against CQ.
